# Generated by Django 3.1 on 2020-09-04 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pljob',
            name='wx_address',
        ),
        migrations.AddField(
            model_name='pljob',
            name='es_query',
            field=models.CharField(default='', max_length=300, verbose_name='查询命令'),
        ),
    ]
