# Generated by Django 3.1 on 2020-09-04 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0002_auto_20200904_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='pljob',
            name='es_query_num',
            field=models.IntegerField(default=1, verbose_name='查询数量'),
        ),
    ]
