# Generated by Django 3.1 on 2020-09-09 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0003_pljob_es_query_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='pljob',
            name='system_type',
            field=models.IntegerField(default=0, verbose_name='系统类型'),
        ),
    ]
