# Generated by Django 3.1 on 2020-10-06 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0004_pljob_system_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlTaskSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(default='', max_length=64, verbose_name='任务名称')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态(1:开,0:关)')),
                ('es_host', models.CharField(default='', max_length=100, verbose_name='ES 主机名')),
                ('es_ip', models.CharField(default='', max_length=64, verbose_name='ES ip 地址')),
                ('es_sechma', models.CharField(default='http', max_length=6, verbose_name='ES 访问协议')),
                ('compress', models.SmallIntegerField(default=0, verbose_name='压缩(1:开,0:关)')),
                ('auth_user', models.CharField(default='', max_length=100, verbose_name='ES 用户名')),
                ('auth_pwd', models.CharField(default='', max_length=100, verbose_name='ES 密码')),
                ('query_string', models.CharField(default='', max_length=500, verbose_name='查询条件')),
                ('query_type', models.CharField(default='', max_length=20, verbose_name='查询类型')),
                ('wx_bot_addr', models.CharField(default='', max_length=100, verbose_name='企业微信机器人地址')),
                ('template', models.TextField(default='', verbose_name='推送文本')),
                ('placeholders', models.TextField(default='', verbose_name='占位符JSON数组')),
                ('delay_sec', models.IntegerField(default=1, verbose_name='每隔多少秒查询一次 ES 服务器')),
                ('push_min', models.IntegerField(default=0, verbose_name='查询到多少条结果触发推送')),
                ('max_per_hour', models.FloatField(default=0.0, verbose_name='每小时推送限制')),
            ],
        ),
        migrations.AddField(
            model_name='pljob',
            name='task_setting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pltplconf.pltasksetting'),
        ),
    ]
