# Generated by Django 3.1 on 2020-10-07 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0007_auto_20201007_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pljob',
            name='task_setting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pltplconf.pltasksetting'),
        ),
    ]
