# Generated by Django 3.1 on 2020-10-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0008_auto_20201007_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlPushLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_pri_key', models.IntegerField(db_index=True, default=0, verbose_name='Job主键ID')),
                ('push_time', models.DateTimeField(db_index=True, verbose_name='推送时间')),
            ],
        ),
    ]
