# Generated by Django 3.1 on 2020-10-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0010_pltasksetting_kbn_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlExportJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_setting_id', models.IntegerField(unique=True, verbose_name='PlTaskSetting主键')),
                ('status', models.SmallIntegerField(default=0, verbose_name='状态(0无任务,1已提交,2运行中)')),
                ('run_time', models.DateTimeField(verbose_name='开始运行的时间')),
                ('req_stop', models.SmallIntegerField(default=0, verbose_name='请求停止任务？')),
                ('process', models.FloatField(default=0.0, verbose_name='进度')),
                ('worker_name', models.CharField(default='', max_length=50, verbose_name='工作进程名称')),
                ('download_addr', models.CharField(default='', max_length=150, verbose_name='文件下载地址')),
                ('task_setting_info', models.TextField(default='', verbose_name='任务设置JSON')),
                ('export_setting_info', models.TextField(default='', verbose_name='导出设置JSON')),
            ],
        ),
    ]
