# Generated by Django 3.1 on 2020-10-26 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0011_plexportjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pltasksetting',
            name='url_prefix',
            field=models.CharField(default='elasticsearch', max_length=15, verbose_name='前缀'),
        ),
    ]
