# Generated by Django 3.1 on 2020-10-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pltplconf', '0012_pltasksetting_url_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='pltasksetting',
            name='es_port',
            field=models.CharField(default='', max_length=6, verbose_name='端口号'),
        ),
    ]
